import 'package:flutter/material.dart';
  const eBackgroundcolor = Colors.black;
  const ePrimaryColor = Color(0xFF39FF14);
  const eSecondaryColor = Color(0xFF265DAB);
  const egreen = Colors.greenAccent;
  const ered = Colors.red;
  const eblue = Colors.blue;
  const eblack = Colors.black;
  const ewhite = Colors.white;
  const egrey=Colors.grey;